Public Map - Observation Activities and Disabled IAPP OnClick Redirect
bcgov/invasivesbc pull request #1905
Opened 2022-05-18 17:38 UTC by bburciaga

# Overview

This PR includes the following proposed change(s):

- Updated so IAPP on click doesn't allow to redirect to iapp site page if not authorized
- Shows submitted activities, but only for Observations

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Screenshots

<img width="1002" alt="Screen Shot 2022-05-18 at 10 36 33 AM" src="https://user-images.githubusercontent.com/52196460/169106879-58eadd92-3f37-4507-8284-2f0f957eea49.png">

<img width="1007" alt="Screen Shot 2022-05-18 at 10 36 17 AM" src="https://user-images.githubusercontent.com/52196460/169106916-0461a73f-fc60-4574-8d05-9e35c3c8780c.png">

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2022-05-26 23:30 UTC, micheal-w-wells requested changes
we actually just want to open up the lean endpoints to be public - not the main points of interest endpoint otherwise people can pull all the iapp data they want

2022-06-08 21:01 UTC, sam-warren submitted a review, later dismissed

2022-06-08 21:01 UTC, sam-warren commented on api/src/models/activity.ts
> +  hideTreatmentsAndMonitoring: any;
boolean?

2022-06-08 22:48 UTC, micheal-w-wells requested changes

2022-06-08 22:48 UTC, micheal-w-wells commented on api/src/paths/activities-lean.ts
> +      const sqlStatement: SQLStatement = getActivitiesLeanSQL(sanitizedSearchCriteria, req);
I think you can remove req here because you updated the criteria object

2022-06-08 22:48 UTC, micheal-w-wells commented on api/src/queries/activity-queries.ts
> +export const getActivitiesLeanSQL = (searchCriteria: ActivitySearchCriteria, req?: InvasivesRequest): SQLStatement => {
I think req can be removed here too

2022-06-08 22:48 UTC, micheal-w-wells commented on api/src/paths/activities-lean.ts
> +    if (!roleName || !roleName.includes('plant') && !roleName.includes('admin')) {
super close I think we just want the && to be ||

2022-06-09 22:26 UTC, micheal-w-wells approved these changes

2022-06-09 22:26 UTC, merged