Redux 2 - Activity Create Tested Working
bcgov/invasivesbc pull request #1991
Opened 2022-06-22 02:04 UTC by plasticviking

# Overview

This PR includes the following proposed change(s):

- {List all the changes, if possible add the linked issue/ticket #}

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Screenshots

Please add any relevant UI screenshots if applicable.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2022-06-23 21:41 UTC, sam-warren requested changes
Looks good but uncovered a few bugs in testing:

- Logout not working / not wired up
- Userinfo in TabsContainer is not wired up properly - unauthenticated user can see all tabs. Likely due to the initialization of the user info object in the store.
- Errors in requests to paths that should be public
- "Record Category" when creating a new record fails to fetch dropdown items
- "Plan My Trip" is visible on web when it should not be, feature gate not working
- There is currently no way to grab IDIR userid and BCEID userid. Need to either include those in extended info OR refactor to remove all occurrences of them if they are redundant.

2022-06-23 21:41 UTC, sam-warren commented on app/src/state/reducers/index.ts
> +    UserInfo: createUserInfoReducer({ loaded: true, accessRequested: false, activated: true }),
Should this be initalized to activated: false? Activated determines whether or not a user's account has been activated by an admin and determines what tabs they can see when they first hit the site. By setting this as default true we're showing all the tabs to anyone who hits the site. Same goes for loaded: should probably be default false and set to true once the extendedInfo is ready.

2022-06-23 21:41 UTC, sam-warren commented on app/src/components/tabs/TabsContainer.tsx
> +    dispatch({ type: 'AUTH_SIGNOUT_REQUEST' });
This doesn't appear to be wired up to anything.

2022-06-23 21:42 UTC, sam-warren commented on app/src/state/sagas/auth.ts
> +        'Access-Control-Allow-Origin': '*'
Is this safe?

2022-06-24 21:31 UTC, micheal-w-wells approved these changes

2022-06-24 21:41 UTC, micheal-w-wells commented
Great stuff - happy to see some state management refactoring... let's shrink changeset size and go for more incremental moving forward so we can catch branches vulnerable to git gotchas (like reverted PR's changing hashes causing conflicts, etc), and also make them easier to review, merge, and catch breaks before they get too big.

2022-06-24 21:41 UTC, merged