New elevation column
bcgov/invasivesbc pull request #231
Opened 2020-12-02 18:16 UTC by popkinj

## Loading of contextual data, including elevation.

This PR includes logic for filling the activity incoming table with contextual data that is not available in the field.
@NickPhura - There is bare SQL in the new component file. It's there for development purposes only. When I've completed the rest of the fields I'll move into separate query files that imported ala the rest of the project.

2020-12-02 18:51 UTC, NickPhura requested changes

2020-12-02 18:51 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +const defaultLog = getLogger('activity');
```suggestion
const defaultLog = getLogger('context-queries');
```

2020-12-02 18:51 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
Is this making an API call to this API, to itself? (If I am misreading this then ignore the below)

If so, we definitely don't want to do that.  We should just pull the logic from the other endpoint into some re-usable functions, and then both endpoints can leverage it directly.

2020-12-02 18:51 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +  const url = `${api}/context/elevation?lon=${x}&lat=${y}`;
Same comment as above.

2020-12-02 18:51 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +    axios.get(url,config)
Same comment as above.

2020-12-02 18:51 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +        `;
This sql is duplicated a few times in this file.  Would be good to move it into its own function, and then it can be re-used.

2020-12-02 18:54 UTC, popkinj commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
Hey @NickPhura 
This may be an opinion thing. I've always considered it best practices for an API to consume it's own resources.

2020-12-02 18:55 UTC, popkinj commented on api/src/utils/context-queries.ts
> +        `;
Good eye @NickPhura 
Yes there is a lot of duplication... I will most likely optimize things when I've completed all the data loaders. I'm just doing this PR a tad prematurely to get dev running again.

2020-12-02 18:59 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
I agree the logic shouldnt be duplicated, but if the code from the other endpoint is pulled into a common function, then both of these endpoints can leverage it the same way. So they would both be doing things the same way, with the same result.  But you wouldn't need all of the extra axios/authorization code, and it wouldn't tack on an extra http request, which is the slowest part of the operation by far.

2020-12-02 19:03 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
It would also help resolve your concurrency issue, because instead of calling 3 distinct endpoints via HTTP, you can just set up a transaction and make 3 sql calls, and then commit it.

And if the sql is created by a function that both endpoints leverage, then there is no issue in that being different either.

2020-12-02 19:06 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
This article articulates some of the reasoning better than mysef: https://softwareengineering.stackexchange.com/questions/345406/is-it-bad-design-to-internally-call-api-endpoints-from-within-the-api-instance

2020-12-02 19:09 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
@micheal-w-wells probably on you to decide ultimately which way we go with this kind of thing, as you'll be maintaining it longer-term.

2020-12-02 19:10 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +        `;
Gotcha, no worries then

2020-12-02 19:30 UTC, popkinj commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
Yeah.... those are good points... again. I think this is an opinion thing.
Having our own services for collecting data allows for other services to use them. It also allows for more flexibility when it comes to dataBC services that are protected... or in a format that isn't appropriate. Also the coordinate transforms can't directly access the database.

2020-12-02 19:34 UTC, sdevalapurkar commented on api/src/utils/context-queries.ts
> + * @param id {integar} The record ID for the activity recently
```suggestion
 * @param id {integer} The record ID for the activity recently
```

2020-12-02 19:34 UTC, sdevalapurkar commented on api/src/utils/context-queries.ts
> +};
```suggestion
};

```

2020-12-02 19:34 UTC, NickPhura commented on api/src/paths/activity.ts
> +      commitContext(result,req);
This could be moved into the transaction above, and then the existing `connection` could be passed into it as a param.  And then if the `commit` function executes some SQL, it will all be part of this same transaction.

2020-12-02 19:42 UTC, popkinj commented on api/src/paths/activity.ts
> +      commitContext(result,req);
That's a good idea. It make take care of the lock errors as well.

2020-12-02 20:06 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
I'm not sure I follow. I'm not suggesting that you get rid of the endpoints you've created, if they are useful for others.

All I'm saying is that this `commit` function may as well call the elevation/databc/etc endpoint code directly, rather than making an HTTP call to itself.

What I mean, as an example, is that the `/context/internal/{target}.ts` endpoint really just needs to wrap some logic in a bit of request/response handling.  But the core logic that matters could live in a re-usable function outside of that file.  And then the `/context/internal/{target}.ts` endpoint an just call it, and simply wrap the return value in a `res(200)` type call, as appropriate.  And then the `commit` function can also call it, but internally without needing all of the http request logic.

2020-12-02 20:17 UTC, NickPhura commented on api/src/paths/activity.ts
> +      commitContext(result,req);
This also needs to be added to the `updateActivity` function below as well.

2020-12-02 21:08 UTC, popkinj commented on api/src/utils/context-queries.ts
> +    const url = `${api}/context/databc/${layer.tableName}?lon=${x}&lat=${y}`;
Oh right. I see what you're saying. Yeah... that's definitely doable.

2020-12-02 21:13 UTC, popkinj commented on api/src/paths/activity.ts
> +      commitContext(result,req);
Nice catch... done.

2020-12-02 21:14 UTC, popkinj commented on api/src/utils/context-queries.ts
> + * @param id {integar} The record ID for the activity recently
haha... a copied spelling mistake. Fixed.

2020-12-02 21:16 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const url = `${api}/context/elevation?lon=${x}&lat=${y}`;
Future enhancement.

2020-12-02 21:16 UTC, popkinj commented on api/src/utils/context-queries.ts
> +    axios.get(url,config)
Future enhancement.

2020-12-02 21:16 UTC, popkinj commented on api/src/utils/context-queries.ts
> +const defaultLog = getLogger('activity');
Done

2020-12-03 18:19 UTC, NickPhura approved these changes

2020-12-03 19:27 UTC, merged