Race condition
bcgov/invasivesbc pull request #438
Opened 2021-01-17 23:50 UTC by popkinj

# Overview

This PR includes the following proposed change(s):

- Refactoring SQL insert logic to occur in bulk. This fixes the Database Locking race condition witnessed before.
- Adding a test overlay which is connected to the offline functionality.
- Fixed a bug where the latitude and longitude were switched on data requests.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

2021-01-18 16:20 UTC, micheal-w-wells approved these changes, later dismissed

2021-01-18 16:38 UTC, sdevalapurkar requested changes

2021-01-18 16:38 UTC, sdevalapurkar commented on api/src/paths/context/databc/{wfs}.ts
> +        //console.log('response from databc: ', response.data);
Can we remove this line now?

2021-01-18 16:38 UTC, sdevalapurkar commented on api/src/paths/context/internal/{target}.ts
> +
Same with this section of commented out code, can it be removed now?

2021-01-18 16:38 UTC, sdevalapurkar commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Instead of using x and y to name these can we just use lat and long as variable names? Would be maybe less ambiguous

2021-01-18 17:06 UTC, sdevalapurkar commented
also I see the linting checks are failing, this needs to be fixed prior to merge :)

2021-01-18 17:28 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
I don't think `activity_data` is available from the body, its a property of `form_data`

`req.body.form_data.activity_data.latitude;`

2021-01-18 18:10 UTC, popkinj commented on api/src/paths/context/databc/{wfs}.ts
> +        //console.log('response from databc: ', response.data);
Yeah totally.

2021-01-18 18:11 UTC, popkinj commented on api/src/paths/context/internal/{target}.ts
> +
Good eye @sdevalapurkar :)

2021-01-18 18:12 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Nice one @NickPhura ... Right you are.

2021-01-18 18:48 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Hmmmm... I'm not seeing the `form_body` key anymore. This is the print out of request *req.body*.
```javascript
{
  activity_id: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
  activity_type: 'Observation',
  activity_subtype: 'Terrestrial Invasive Plant',
  date: '2019-04-12',
  deviceRequestUID: 'string',
  created_timestamp: '2018-11-13T20:20:39+00:00',
  geometry: [ { type: 'Feature', geometry: [Object], properties: {} } ],
  activity_data: { latitude: 49.29153, longitude: -124.95511, reported_area: 10 },
  activity_type_data: {
    negative_observation_ind: false,
    aquatic_observation_ind: false,
    primary_user_last_name: 'mike',
    secondary_user_first_name: 'mike',
    secondary_user_last_name: 'mike',
    species: 'banana',
    primary_file_id: 'test',
    secondary_file_id: 'test',
    location_comment: 'test',
    general_observation_comment: 'general comment',
    sample_label_number: 'string'
  },
  activity_subtype_data: {
    species: 'banana',
    distribution: 123,
    density: 123,
    soil_texture: 1,
    slope: 123,
    aspect: 123,
    flowering: true,
    specific_use: 123,
    proposed_action: 123,
    seed_stage: 123,
    plant_health: 123,
    plant_life_stage: 123,
    early_detection: 1,
    research: true,
    well_on_site_ind: true,
    special_care_ind: true,
    biological_care_ind: true,
    legacy_site_ind: true,
    range_unit: 'Canyon'
  }
}
```

2021-01-18 18:53 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Good point @sdevalapurkar .... However this is a common syntax for portraying coordinates.

2021-01-18 19:10 UTC, sdevalapurkar commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
ok sounds good! was just wondering

2021-01-18 19:11 UTC, sdevalapurkar commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
how are you getting this to print? is it a request through postman?

2021-01-18 19:16 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
I'm printing to the console when an activity is submitted.

2021-01-18 19:16 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
It's the request body that the client is submitting to the API.

2021-01-18 19:23 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Oh... I get what you're saying @sdevalapurkar 
Maybe I'm sending an outdated data package.

2021-01-18 19:25 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Hmmmm.... I don't have postman running yet. Can someone give me an example data POST/PUT payload? That is current?

2021-01-18 19:31 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Id have to side with shreyas on this one.  Mainly because the switch from 'latitude' to 'x' doesn't really benefit anyone.  If you were trying to track down where latitudes are used, or trying to decipher some code farther down the stack, seeing 'x' is not particularly informative.  Especially if you aren't a spatial developer who knows that 'x' means latitude.

2021-01-18 19:31 UTC, micheal-w-wells commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
I think I broke my postman setup.  A way to get up to date version is to fillout a plant observation here https://dev-invasivesbci.apps.silver.devops.gov.bc.ca/home/activities and then hit reviewed and sync on the 'my activities page' with the network tab open in chrome.  Look at request headers and scroll down.

2021-01-18 19:32 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Hmm, it must have been parsed out earlier in the code I guess?

2021-01-18 19:34 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Sure... I can make the switch.

2021-01-18 19:38 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Never mind... Just install Postman.

2021-01-18 19:43 UTC, NickPhura commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
This is the request body that is sent from the frontend:

```Typescript
{
    activity_id: activity.activityId,
    created_timestamp: activity.dateCreated,
    activity_type: activity.activityType,
    activity_subtype: activity.activitySubtype,
    geometry: activity.geometry,
    media:
        activity.photos &&
        activity.photos.map((photo) => {
        return { file_name: photo.filepath, encoded_file: photo.dataUrl };
        }),
    form_data: activity.formData
}
```

And then the form_data field should just have that blob you pasted before in it.

2021-01-18 19:49 UTC, NickPhura commented
> 
> 
> also I see the linting checks are failing, this needs to be fixed prior to merge :)

For the app, can just run `npm run lint:fix`.  It will lint all files, but if the linting is up to date (which I believe it is) it should only catch linting issues in newly changed files.

2021-01-18 20:16 UTC, sdevalapurkar commented
> > also I see the linting checks are failing, this needs to be fixed prior to merge :)
> 
> For the app, can just run `npm run lint:fix`. It will lint all files, but if the linting is up to date (which I believe it is) it should only catch linting issues in newly changed files. It will generally auto fix all of them, and list any it was unable to.
> 
> Though there might be a few lint items that we have chosen to ignore, for now? Correct me if I am wrong @sdevalapurkar
> Wait, starting to remember now, those ones just come up as warnings, rather than errors.

Yup all errors need to be fixed before merge. It is considered a blocker for PR. Warnings that can be addressed should be but not a blocker as some of lints suggestions for warnings cause app to break

2021-01-18 20:18 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Good thinking @micheal-w-wells ... That sounds like the best way to get the current schema.

2021-01-18 20:21 UTC, popkinj commented
Think I've fixed all the linting errors which I introduced.

---------
Jamie Popkin
Little Earth
250 390 6816
https://littleearth.ca



On Mon, Jan 18, 2021 at 12:16 PM Shreyas Devalapurkar <
notifications@github.com> wrote:

> also I see the linting checks are failing, this needs to be fixed prior to
> merge :)
>
> For the app, can just run npm run lint:fix. It will lint all files, but
> if the linting is up to date (which I believe it is) it should only catch
> linting issues in newly changed files. It will generally auto fix all of
> them, and list any it was unable to.
>
> Though there might be a few lint items that we have chosen to ignore, for
> now? Correct me if I am wrong @sdevalapurkar
> <https://github.com/sdevalapurkar>
> Wait, starting to remember now, those ones just come up as warnings,
> rather than errors.
>
> Yup all errors need to be fixed before merge. It is considered a blocker
> for PR. Warnings that can be addressed should be but not a blocker as some
> of lints suggestions for warnings cause app to break
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bcgov/invasivesbc/pull/438#issuecomment-762452431>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADU6YSBKDQKBQRMZYFMI5LS2SJK7ANCNFSM4WGQDXCQ>
> .
>

2021-01-18 20:35 UTC, sdevalapurkar commented
There seem to still be failures here: https://github.com/bcgov/invasivesbc/pull/438/checks?check_run_id=1723476596#step:5:13

2021-01-18 20:47 UTC, popkinj commented
Yeah... I see that. I can't figure out what it's complaining about.

2021-01-18 20:49 UTC, sdevalapurkar commented
> Yeah... I see that. I can't figure out what it's complaining about. Do you think the linter doesn't like the spaces?

Let me help you out

2021-01-18 20:49 UTC, popkinj commented
> > Yeah... I see that. I can't figure out what it's complaining about. Do you think the linter doesn't like the spaces?
> 
> Let me help you out

I just made the layer identical to the previous ones. Let's see how it does.

2021-01-18 20:53 UTC, sdevalapurkar commented
my most recent commit should make the action pass @popkinj

2021-01-18 20:53 UTC, popkinj commented
Hey, what linter extension do you guys use?

2021-01-18 21:10 UTC, popkinj commented on api/src/utils/context-queries.ts
> +  const x = req.body.activity_data.longitude;
Thanks @NickPhura ... Yeah, I just verified the `form_data` is a thing.
I'm going to fix all the logic to match... Let's keep this branch going until I do.

2021-01-18 21:23 UTC, sdevalapurkar commented
should pass now @popkinj

2021-01-18 21:36 UTC, sdevalapurkar reviewed
looks good to me other than nick's comments left to address regarding `form_data` and `x`, `y`, `lat`, `lng`

2021-01-18 21:36 UTC, sdevalapurkar commented on api/test/observation-polygon.json
> +}
```suggestion
}

```

2021-01-18 22:17 UTC, NickPhura commented on api/src/paths/context/internal/{target}.ts
> +        public.st_geographyFromText('POINT(${lon} ${lat})'),
Just double checking, there doesnt need to be a comma between lon and lat?

2021-01-18 22:48 UTC, popkinj commented on api/src/paths/context/internal/{target}.ts
> +        public.st_geographyFromText('POINT(${lon} ${lat})'),
Correct... haha. That one always get's me too @NickPhura . It's a text representation of spatial stuff called [Well Known Text](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry). Thanks for checking though.

2021-01-19 00:03 UTC, popkinj commented
Think we're all good here. Any last objections?

2021-01-19 00:25 UTC, sdevalapurkar reviewed
I see 3 warnings about missing dependencies, does adding them break anything? or can they be added to comply with the lint checker? @popkinj

2021-01-19 00:29 UTC, sdevalapurkar approved these changes
Just a question about the missing dependencies in hooks, but otherwise LGTM!! 💯

2021-01-19 00:43 UTC, merged