Bulk Deletions - app and api
bcgov/invasivesbc pull request #473
Opened 2021-01-27 04:39 UTC by dogcomplex

# Overview

Adds endpoints:

- DELETE /api/activities  to delete a list of activities by their id
- POST /api/deleted/activities  to undelete a list of activities by their id

As well as UI for bulk Deletion on the Activities search page.

Deletion is actually soft-deletion, just setting deleted_timestamp to the current time.  Undeletion is more complex - only un-deleting the latest version.  Might want to adapt that into an "Undo" control which effectively bumps the non-deleted record down the list, or just creates a new record with deleted_timestamp NULL.  Either way - too much effort on too inconsequential details.  Same reasoning there's no UI for undeletion yet.

This PR includes the following proposed change(s):

- https://github.com/bcgov/invasivesbc/issues/316

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Tested locally with dev data.  Deletion UI working

## Screenshots

![2021-01-26 20_24_46-InvasivesBC - Search](https://user-images.githubusercontent.com/4359195/105943606-75648100-6016-11eb-86b8-86fe469bd4e0.png)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] New and existing unit tests pass locally with my changes

2021-01-27 17:29 UTC, sdevalapurkar approved these changes

2021-01-27 17:29 UTC, sdevalapurkar commented on api/src/paths/activities.ts
> +import { getActivitiesSQL, deleteActivitiesSQL, undeleteActivitiesSQL } from '../queries/activity-queries';
remove `undeleteActivitiesSQL` as it is not used

2021-01-27 17:29 UTC, sdevalapurkar commented on api/src/paths/deleted/activities.ts
> +import { ActivitySearchCriteria } from '../../models/activity';
remove `ActivitySearchCriteria` as it is unused

2021-01-27 17:29 UTC, sdevalapurkar commented on api/src/paths/deleted/activities.ts
> +import geoJSON_Feature_Schema from '../../openapi/geojson-feature-doc.json';
same with geoJSON_Feature_Schema

2021-01-27 17:29 UTC, sdevalapurkar commented on api/src/paths/deleted/activities.ts
> +import { getActivitiesSQL, deleteActivitiesSQL, undeleteActivitiesSQL } from '../../queries/activity-queries';
same with getActivitiesSQL and deleteActivitiesSQL

2021-01-27 17:29 UTC, sdevalapurkar commented on app/src/components/search/SearchResultsList.tsx
> +import { DatabaseContext } from 'contexts/DatabaseContext';
remove DatabaseContext

2021-01-27 17:29 UTC, sdevalapurkar commented on app/src/components/search/SearchResultsList.tsx
> +              history.go(0);
supernit:

might be able to just say: `history.go()`

2021-01-27 17:30 UTC, sdevalapurkar requested changes
LGTM, just need to address the code smells and duplication before merge

2021-01-27 17:33 UTC, dogcomplex commented on app/src/components/search/SearchResultsList.tsx
> +              history.go(0);
Compiler errors, so apparently not

2021-01-27 17:39 UTC, sdevalapurkar commented on app/src/components/search/SearchResultsList.tsx
> +              history.go(0);
hmm interesting, maybe does not work with react-router

2021-01-27 19:11 UTC, dogcomplex commented
> LGTM, just need to address the code smells and duplication before merge

Got most of them.  Can we squash the rest?  
- Removing the "unnecessary" typing creates new typing errors due to ambiguity and it used in other endpoints.  
- The POST/DELETE operations are used despite its protests - though not sure why those are being flagged while the POST for getActivities is not (any thoughts on that?). 
- Code duplication:  I'm not in the mood to make a generalized SQL query connector/executor just to save a dozen lines of code.  Hard pass for this PR, and the same crime has been committed many times with other endpoints.

2021-01-27 19:22 UTC, sdevalapurkar commented
I think these code smells can be fixed: 

- https://sonarcloud.io/project/issues?id=bcgov_invasivesbc&open=AXdFNQDhJdVl9hNwWZaD&pullRequest=473&resolved=false&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=bcgov_invasivesbc&open=AXdFLdUuBFS7daocb3PX&pullRequest=473&resolved=false&types=CODE_SMELL

2021-01-27 19:25 UTC, sdevalapurkar commented
the duplication can be fixed too -> just a function that peforms this logic:
<img width="479" alt="1" src="https://user-images.githubusercontent.com/28017034/106042748-53104900-6092-11eb-908c-b0cbffa0bc32.png">

just needs a param to allow it to determine whether it is deleting or undeleting but the rest of the code is shared

2021-01-28 22:50 UTC, sdevalapurkar approved these changes, later dismissed

2021-01-28 22:54 UTC, sdevalapurkar commented on app/src/components/search/SearchResultsList.tsx
> +            onClick={() => navigateToBulkEditPage(editIds)}>
```suggestion
            onClick={() => navigateToEditPage(editIds)}>
```

2021-01-28 22:54 UTC, sdevalapurkar approved these changes

2021-01-28 23:00 UTC, merged