Context Layers for the Map
bcgov/invasivesbc pull request #544
Opened 2021-02-22 23:08 UTC by popkinj

# Overview

This PR includes the following new layers for the map:

- Ownership
- Wells
- Invasive Plant Management Areas
- Regional Invasive Species Organization Areas
- Gravel Pits
- Streams
- Wetlands
- Municipalities
- Regional Districts
- Natural Resource Districts
- Road Features Inventory
- Basemap Place Names

All have been configured for availability offline.

2021-02-23 03:57 UTC, micheal-w-wells requested changes

2021-02-23 03:57 UTC, micheal-w-wells commented on app/src/components/map/MapContainer.tsx
> +    return L.tileLayer.offline('http://localhost:8080/geoserver/gwc/service/tms/1.0.0/invasives:WHSE_ADMIN_BOUNDARIES.ADM_NR_DISTRICTS_SPG@EPSG:900913@png/{z}/{x}/{y}.png',{
Don't we need to substitute the domain here based on some env var?

2021-02-23 03:57 UTC, micheal-w-wells commented on app/src/components/map/MapContainer.tsx
> +      opacity: 0.8,
Can you run vscode format / lint fix on MapContainer.tsx while you are in there?

2021-02-23 03:57 UTC, micheal-w-wells commented on app/src/components/map/MapContainer.css
> +  transform: translate(-7px, 20px);
Did you try this mocking out a mobile layout?

2021-02-23 16:06 UTC, popkinj commented on app/src/components/map/MapContainer.tsx
> +    return L.tileLayer.offline('http://localhost:8080/geoserver/gwc/service/tms/1.0.0/invasives:WHSE_ADMIN_BOUNDARIES.ADM_NR_DISTRICTS_SPG@EPSG:900913@png/{z}/{x}/{y}.png',{
Good catch @micheal-w-wells .... Yes, this should be an env variable.

2021-02-23 16:07 UTC, popkinj commented on app/src/components/map/MapContainer.tsx
> +      opacity: 0.8,
Sure.

2021-02-23 16:07 UTC, popkinj commented on app/src/components/map/MapContainer.css
> +  transform: translate(-7px, 20px);
No I didn't. I'll see what it looks like on an iPad.

2021-02-23 21:09 UTC, popkinj commented on app/src/components/map/MapContainer.tsx
> +    return L.tileLayer.offline('http://localhost:8080/geoserver/gwc/service/tms/1.0.0/invasives:WHSE_ADMIN_BOUNDARIES.ADM_NR_DISTRICTS_SPG@EPSG:900913@png/{z}/{x}/{y}.png',{
Hmmm... Thinking maybe we should be proxying this through the API.

2021-02-23 21:10 UTC, popkinj commented on app/src/components/map/MapContainer.tsx
> +    return L.tileLayer.offline('http://localhost:8080/geoserver/gwc/service/tms/1.0.0/invasives:WHSE_ADMIN_BOUNDARIES.ADM_NR_DISTRICTS_SPG@EPSG:900913@png/{z}/{x}/{y}.png',{
That way we don't have to worry about the HTTPS-> HTTP issue. And we'll get the benefit of Keycloak.

2021-02-23 21:21 UTC, micheal-w-wells commented on app/src/components/map/MapContainer.tsx
> +    return L.tileLayer.offline('http://localhost:8080/geoserver/gwc/service/tms/1.0.0/invasives:WHSE_ADMIN_BOUNDARIES.ADM_NR_DISTRICTS_SPG@EPSG:900913@png/{z}/{x}/{y}.png',{
Until that is done will merging this break the app?

2021-02-23 23:49 UTC, popkinj commented
Hey @micheal-w-wells 
I've run the linter and made some updates to the URL logic to Geoserver. I'd like to eventually proxy Geoserver through the API. That would allow us to use environment variables and the like instead of forming the path in the front end.

2021-02-24 16:26 UTC, popkinj commented on app/src/components/map/MapContainer.tsx
> +      opacity: 0.8,
I couldn't get the vscode extension to work... So I installed the linter separately, ran it, and fixed all the complaints.

2021-02-24 17:13 UTC, micheal-w-wells commented on app/src/components/map/MapContainer.tsx
> +      opacity: 0.8,
either didn't get pushed up or your linter is different - seemed to have a bunch more issues than before.  I ran it for you

2021-02-24 17:14 UTC, merged

2021-02-24 17:14 UTC, micheal-w-wells commented
@popkinj your branch to delete when ready - remember to do a pull before you add more work to it if that was your plan.

2021-02-24 17:15 UTC, popkinj commented
Got it. Thanks @micheal-w-wells